version: '3'

services:
  poll:
    build: ./poll
    ports:
      - "5000:80"
    environment:
      - REDIS_HOST=redis
    networks:
      - poll-tier
    depends_on:
      - redis
    restart: always

  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    networks:
      - poll-tier
      - back-tier
    restart: always

  worker:
    build: ./worker
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=database_name
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - back-tier
    depends_on:
      - redis
      - db
    restart: always

  db:
    image: postgres:16
    environment:
      - POSTGRES_DB=database_name
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - result-tier
      - back-tier
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    restart: always

  result:
    build: ./result
    ports:
      - "5001:80"
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=database_name
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - result-tier
    depends_on:
      - db
    restart: always


networks:
  poll-tier:
  result-tier:
  back-tier:

volumes:
  db-data: